import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './_components/shared/navigation/Navigation';
import ThemeProvider from './_components/shared/providers/ThemeProvider';
import QueryProvider from './_store/QueryClientProvider';
import ScrollToTop from './_components/shared/ScrollToTop';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Game Gear Hub',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ThemeProvider attribute='class'>
                    <QueryProvider>
                        <Navigation />
                        {children}
                        <Toaster />
                        <ScrollToTop />
                    </QueryProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
